[package]
name = "tiro-derive"
version = "0.1.0"
edition = "2024"

[lib] 
proc-macro = true

[dependencies]
proc-macro-crate = "3.4.0"
proc-macro-error = "1.0.4"
proc-macro2 = "1.0.103"
quote = "1.0.41"
syn = "2.0.108"

